services:
  db:
    image: postgres:15-alpine
    container_name: online-exam-db
    environment:
      POSTGRES_USER: exam_user
      POSTGRES_PASSWORD: exam_password
      POSTGRES_DB: online_exam
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: online-exam-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning

  backend:
    build: ./backend
    container_name: online-exam-backend
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://exam_user:exam_password@db:5432/online_exam
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=vnuis_secret_key_2026
    restart: unless-stopped
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL=https://fdbtalent.vnuis.edu.vn/api/v1
    container_name: online-exam-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://fdbtalent.vnuis.edu.vn/api/v1
      - NEXTAUTH_URL=https://fdbtalent.vnuis.edu.vn
      - NEXTAUTH_SECRET=vnuis_nextauth_secret
    restart: unless-stopped

volumes:
  pgdata:
