"""Add exam landing config and student profile

Revision ID: 3bb3a8ae729a
Revises: e52cb1e3d445
Create Date: 2026-03-27 16:02:00.054226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3bb3a8ae729a'
down_revision: Union[str, Sequence[str], None] = 'e52cb1e3d445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('end_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('exams', sa.Column('landing_config', sa.JSON(), nullable=True))
    op.alter_column('exams', 'theme_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('questions', 'options',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.add_column('students', sa.Column('cccd', sa.String(), nullable=True))
    op.add_column('students', sa.Column('address', sa.String(), nullable=True))
    op.add_column('students', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('students', sa.Column('email', sa.String(), nullable=True))
    op.add_column('students', sa.Column('lien_chi_doan', sa.String(), nullable=True))
    op.drop_constraint(op.f('uq_students_mssv'), 'students', type_='unique')
    op.drop_constraint(op.f('uq_students_user_id'), 'students', type_='unique')
    op.drop_index(op.f('ix_students_mssv'), table_name='students')
    op.create_index(op.f('ix_students_mssv'), 'students', ['mssv'], unique=True)
    op.drop_index(op.f('ix_students_user_id'), table_name='students')
    op.create_index(op.f('ix_students_user_id'), 'students', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_user_id'), table_name='students')
    op.create_index(op.f('ix_students_user_id'), 'students', ['user_id'], unique=False)
    op.drop_index(op.f('ix_students_mssv'), table_name='students')
    op.create_index(op.f('ix_students_mssv'), 'students', ['mssv'], unique=False)
    op.create_unique_constraint(op.f('uq_students_user_id'), 'students', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_students_mssv'), 'students', ['mssv'], postgresql_nulls_not_distinct=False)
    op.drop_column('students', 'lien_chi_doan')
    op.drop_column('students', 'email')
    op.drop_column('students', 'phone')
    op.drop_column('students', 'address')
    op.drop_column('students', 'cccd')
    op.alter_column('questions', 'options',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('exams', 'theme_config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('exams', 'landing_config')
    op.drop_column('exams', 'end_time')
    # ### end Alembic commands ###
