"""add_slug_and_description_to_exams

Revision ID: 465c28fe8735
Revises: b0e401de9d0e
Create Date: 2026-03-03 17:36:15.304022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '465c28fe8735'
down_revision: Union[str, Sequence[str], None] = 'b0e401de9d0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('slug', sa.String(length=12), nullable=True))
    op.add_column('exams', sa.Column('description', sa.String(), nullable=True))
    op.create_index(op.f('ix_exams_slug'), 'exams', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exams_slug'), table_name='exams')
    op.drop_column('exams', 'description')
    op.drop_column('exams', 'slug')
    # ### end Alembic commands ###
