"""add_org_units_question_pools

Revision ID: 919f011bbf08
Revises: 2aa31311f7c7
Create Date: 2026-02-25 17:43:06.192821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '919f011bbf08'
down_revision: Union[str, Sequence[str], None] = '2aa31311f7c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizational_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizational_units_id'), 'organizational_units', ['id'], unique=False)
    op.create_index(op.f('ix_organizational_units_name'), 'organizational_units', ['name'], unique=True)
    op.create_table('question_pools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('org_unit_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['org_unit_id'], ['organizational_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_pools_id'), 'question_pools', ['id'], unique=False)
    op.create_index(op.f('ix_question_pools_name'), 'question_pools', ['name'], unique=False)
    op.add_column('questions', sa.Column('pool_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'questions', 'question_pools', ['pool_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('org_unit_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'organizational_units', ['org_unit_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'org_unit_id')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'pool_id')
    op.drop_index(op.f('ix_question_pools_name'), table_name='question_pools')
    op.drop_index(op.f('ix_question_pools_id'), table_name='question_pools')
    op.drop_table('question_pools')
    op.drop_index(op.f('ix_organizational_units_name'), table_name='organizational_units')
    op.drop_index(op.f('ix_organizational_units_id'), table_name='organizational_units')
    op.drop_table('organizational_units')
    # ### end Alembic commands ###
