"""add_anti_cheat_columns

Revision ID: b0e401de9d0e
Revises: 919f011bbf08
Create Date: 2026-02-26 22:47:38.553225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0e401de9d0e'
down_revision: Union[str, Sequence[str], None] = '919f011bbf08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('violation_count', sa.Integer(), nullable=True))
    op.add_column('submissions', sa.Column('forced_submit', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'forced_submit')
    op.drop_column('submissions', 'violation_count')
    # ### end Alembic commands ###
